### ISSUE TITLE
不可以直接将一段音频里的多人分类吗

### ISSUE THREAD

**Issue by Jackylee2032** [2DIPW/audio_dataset_vpr#1]
不可以直接将一段音频里的多人分类吗

**Comment by 2DIPW** [comment]
如果你的数据中一段音频就有多个说话人，你需要先用[切片机](https://github.com/flutydeer/audio-slicer)切开
此项目不负责音频切片

**Comment by Jackylee2032** [comment]
不对啊，我要能分开，我手动分类就行了，还要这个工具干嘛



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月28日(周三) 凌晨0:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [2DIPW/audio_dataset_vpr] 不可以直接将一段音频里的多人分类吗 (Issue #1)




 
如果你的数据中一段音频就有多个说话人，你需要先用切片机切开
 此项目不负责音频切片

**Comment by 2DIPW** [comment]
Readme和项目名都写得很清楚，这个工具的作用是对无标注的游戏解包语音或各类分割成段的混杂**音频数据集**，按照每一段的声纹特征归类说话人。
如果你要将原始的长音频数据按说话人切开，你的需求是**声纹分割聚类（Speaker Diarization）**，如果你要将多个说话人同时说话的音频按说话人不同频段进行分离，你的需求是**声源分离（Source Separation）**，此项目初衷不是为了解决这种应用场景，将来也无计划支持此功能，请使用其他项目。
